services:
  orchestrator:
    build: .
    container_name: orchestrator
    environment:
      - MONGO_USER=iotuser
      - MONGO_PASS=iotpass
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=iot_mesh
      - MONGO_COLLECTION=sensor_data
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=mesh/data/
      - MQTT_KPI_TOPIC=mesh/kpi/
      - MQTT_USERNAME=orchestrator
      - MQTT_PASSWORD=mqtt_pass
      - ENCRYPTION=true
      - ENCRYPT_API_URL=http://cipher-api:8080/
    restart: always